# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brief',
            field=models.CharField(default='', max_length=200),
        ),
    ]
