# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160820_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
