# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160820_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='r01c4',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AddField(
            model_name='post',
            name='r01c6',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AddField(
            model_name='post',
            name='r01c8',
            field=models.CharField(default='', max_length=99),
        ),
    ]
