# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160820_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='r01c4',
            field=models.CharField(default='.', max_length=99),
        ),
        migrations.AlterField(
            model_name='post',
            name='r01c6',
            field=models.CharField(default='.', max_length=99),
        ),
        migrations.AlterField(
            model_name='post',
            name='r01c8',
            field=models.CharField(default='.', max_length=99),
        ),
        migrations.AlterField(
            model_name='post',
            name='r03c3',
            field=models.CharField(default='.', max_length=99),
        ),
        migrations.AlterField(
            model_name='post',
            name='r03c4',
            field=models.CharField(default='.', max_length=99),
        ),
        migrations.AlterField(
            model_name='post',
            name='r03c5',
            field=models.CharField(default='.', max_length=99),
        ),
        migrations.AlterField(
            model_name='post',
            name='r03c6',
            field=models.CharField(default='.', max_length=99),
        ),
        migrations.AlterField(
            model_name='post',
            name='r03c7',
            field=models.CharField(default='.', max_length=99),
        ),
        migrations.AlterField(
            model_name='post',
            name='r04c3',
            field=models.CharField(default='.', max_length=99),
        ),
        migrations.AlterField(
            model_name='post',
            name='r04c4',
            field=models.CharField(default='.', max_length=99),
        ),
        migrations.AlterField(
            model_name='post',
            name='r04c5',
            field=models.CharField(default='.', max_length=99),
        ),
        migrations.AlterField(
            model_name='post',
            name='r04c6',
            field=models.CharField(default='.', max_length=99),
        ),
        migrations.AlterField(
            model_name='post',
            name='r04c7',
            field=models.CharField(default='.', max_length=99),
        ),
    ]
